# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/skanda/Music/prcv_final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/skanda/Music/prcv_final

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skanda/Music/prcv_final/CMakeFiles /home/skanda/Music/prcv_final/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skanda/Music/prcv_final/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prcv_final_project

# Build rule for target.
prcv_final_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prcv_final_project
.PHONY : prcv_final_project

# fast build rule for target.
prcv_final_project/fast:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/build
.PHONY : prcv_final_project/fast

src/helper_functions.o: src/helper_functions.cpp.o

.PHONY : src/helper_functions.o

# target to build an object file
src/helper_functions.cpp.o:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/src/helper_functions.cpp.o
.PHONY : src/helper_functions.cpp.o

src/helper_functions.i: src/helper_functions.cpp.i

.PHONY : src/helper_functions.i

# target to preprocess a source file
src/helper_functions.cpp.i:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/src/helper_functions.cpp.i
.PHONY : src/helper_functions.cpp.i

src/helper_functions.s: src/helper_functions.cpp.s

.PHONY : src/helper_functions.s

# target to generate assembly for a file
src/helper_functions.cpp.s:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/src/helper_functions.cpp.s
.PHONY : src/helper_functions.cpp.s

src/yolo_v5.o: src/yolo_v5.cpp.o

.PHONY : src/yolo_v5.o

# target to build an object file
src/yolo_v5.cpp.o:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/src/yolo_v5.cpp.o
.PHONY : src/yolo_v5.cpp.o

src/yolo_v5.i: src/yolo_v5.cpp.i

.PHONY : src/yolo_v5.i

# target to preprocess a source file
src/yolo_v5.cpp.i:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/src/yolo_v5.cpp.i
.PHONY : src/yolo_v5.cpp.i

src/yolo_v5.s: src/yolo_v5.cpp.s

.PHONY : src/yolo_v5.s

# target to generate assembly for a file
src/yolo_v5.cpp.s:
	$(MAKE) -f CMakeFiles/prcv_final_project.dir/build.make CMakeFiles/prcv_final_project.dir/src/yolo_v5.cpp.s
.PHONY : src/yolo_v5.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... prcv_final_project"
	@echo "... src/helper_functions.o"
	@echo "... src/helper_functions.i"
	@echo "... src/helper_functions.s"
	@echo "... src/yolo_v5.o"
	@echo "... src/yolo_v5.i"
	@echo "... src/yolo_v5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

